### ISSUE TITLE
Candy Tracking

### ISSUE THREAD

**Issue by gseals** [Zack-Taylor/CandyApi#6]
- [x] As a candy owner, I want to be able to keep track of the candy that I receive
  - [x] Create Candy Database
  - [x] Create CandiAPi Project
  - [x] Create Models Folder
    - [x] Create Candi Class
    - [x] Create Flavor Class
  - [x] Create Candi Repo
  - [x] Create Candi Controller 

- [x] As a candy owner, I want to be able to keep track of the candy that I eat
  - [x] I want to make sure that I eat the piece that I received first so that I don't waste candy
  - [x] If I only know what flavor of candy that I want to eat, I want an option that will pick a random piece of candy for me in that category. This option should also not waste old candy.

**Comment by gseals** [comment]
update your own databases with these lines:

```
UPDATE Stash
SET Stash.CandyId = 6
WHERE Stash.StashId = 6


INSERT INTO Candy VALUES('Reese', 'Hershey', 5, '2020-05-19', 0, 1)
INSERT INTO Candy VALUES('Reese', 'Hershey', 5, '2020-05-19', 1, 1)
INSERT INTO Candy VALUES('Reese', 'Hershey', 5, '2020-05-19', 0, 1)
INSERT INTO Candy VALUES('Reese', 'Hershey', 5, '2020-05-19', 0, 1)

**Comment by gseals** [comment]
this query returns all candies by owner that have not been eaten

```
SELECT
	Candy.CandyId,
	Candy.[Name],
        Candy.Manufacturer,
	Candy.FlavorId,
	Candy.DateCollected,
	Candy.Ate,
	Candy.StashId
FROM Candy
JOIN Stash ON Stash.StashId = Candy.StashId
JOIN [User] ON [User].Uid = Stash.UserId
WHERE Candy.Ate = 1 AND [User].uid = 1
ORDER BY Candy.DateCollected, Candy.StashId
